### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#10]
Tried to install and got an error message

![image](https://user-images.githubusercontent.com/5352830/134893848-d7b4d940-94d6-42de-82a1-0753de5477b4.png)

Please mention when applicable:
* python version 3.6.9
* OS version Ubuntu 18
* browser version NA 
* version of dataqa 1.0.6

**Comment by dataqa** [comment]
Hey, thanks for the feedback, I have tried to set up a VM with that version of python and Ubuntu and it works. What's your version of pip? It needs to be above 20.3.

**Comment by talolard** [comment]
Yep that fixed it. I was on version 9 ...
