### ISSUE TITLE
Allow selection of column name in CSV upload

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#12]
I have a csv but the text column is named content, not text. 
As a new user, I have a limited "grace budget" for onboarding, and it doesn't cover opening the csv and renaming the column. I don't yet know what dataqa is, so I can't be bothered (hypothetically). 
Thus when I get the following, I will churn:

![image](https://user-images.githubusercontent.com/5352830/135168405-b50502c1-461f-4679-9121-97d9f55b441f.png)

I'd suggest detecting column names and letting the user select the relevant column. You can use [PapaParse](https://www.papaparse.com/) to parse a csv client side and then let the user select the proper column

**Comment by dataqa** [comment]
Great comment! Thanks so much. As of `v1.1.1`, there is a column selector that shows up if the default column is not found in the file (check it in the [docs](https://dataqa.ai/docs/v1.1.1/file_formats/classification/)). I have used PapaParse behind the scenes to perform a quick check from the client to see if the default columns were present, as suggested. Thank you again!
