### ISSUE TITLE
During onboarding, the upload button should be disabled until a project name is set

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#13]
I uploaded a file by pressing upload, but got an error message because I didn't set a project name.
![image](https://user-images.githubusercontent.com/5352830/135168847-ff73adbf-dc0c-48fb-99dd-d780235e83a8.png)

Instead consider either:

- Disable the upload button until a project name is set (use the disabled prop on the MUI Button) 
- Or, add a second button,"select file" and only show the upload button when a name is set and file selected
- BEST, use the [material ui stepper](https://mui.com/components/steppers/) To let the user know what needs to be done

**Comment by dataqa** [comment]
Thanks again for your comment! I have disabled the upload button in the latest version `v1.1.1` until the project name is set, so no more ugly alert. I hadn't seen the ui stepper, looks great! I will add this to the roadmap, it's exactly what I would like to implement.
