### ISSUE TITLE
I uploaded a file, now what ?

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#14]
I uploaded a file, then I was sent here:
![image](https://user-images.githubusercontent.com/5352830/135169196-b6c1694a-3559-42e6-b1f6-e6746ff07094.png)

I've just been here. What should I do now ? 

As a new user, I'd like you to 

1. Give me a confirmation that my data was uploaded successfully.
2. Now that I'm in a new state (Have data) tell me what to do with it. 

BTW , terminal shows this:

![image](https://user-images.githubusercontent.com/5352830/135169388-49dff511-2db0-43ab-aae0-b0e7ac541c63.png)

So I guess things went well

**Comment by dataqa** [comment]
Hi, I have added an extra step in `v1.1.1` now with a confirmation message that the upload was successful. I hope it makes the flow clearer! You can check it out here: https://dataqa.ai/docs/v1.1.1/file_formats/classification.
