### ISSUE TITLE
Where do I set class names?

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#15]
So I uploaded data and made a project.
I got excited when I could add a rule, but I don't have any classes defined and I don't know where to add them.

![image](https://user-images.githubusercontent.com/5352830/135169650-aad1b638-793f-4b3d-bea4-1a1f92f43e9e.png)

I went to projects but I couldn't find a way to add classes

![image](https://user-images.githubusercontent.com/5352830/135169779-a105dbd9-1924-4062-b4a1-daab4ef6554d.png)

As a new user, I have churned now

**Comment by dataqa** [comment]
Hey, thanks for the feedback! The latest version of the tool `v1.1.1` does not let you continue to the main project page unless you have uploaded a file with the class names, so you should not be seeing this issue anymore.
