### ISSUE TITLE
Onobarding Suggestion: Make docs easier to find

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#6]
I found the documentation on the organization page and they are thorough and helpful, especially the tutorial section.

However, they are hard to find, with a passing mention on the repo page. 
I'd suggest 

1. Add a link to the docs in the repos **about** section
2. In the Readme, add a Docs section with links to each section in the docs

This would make it easier for a potential user to get a sense of what the platform is before deciding to install

**Comment by dataqa** [comment]
Hi, thanks for the suggestions, I made some changes to the README :-)
