### ISSUE TITLE
Onboarding Suggestion: Tell me why I should use this

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#7]
The README opens with a welcome message and a logo, but it doesn't tell me **why** I might want to use this. 

I happen to be in the industry and think about this stuff a lot, so it clicks for me quick. But at this stage of the project, you're probably looking for early adopters who would try it out, and you need to tell them what's the best thing that could happen to them if they do. e.g. "Instead of spending days labeling data you can write a few rules with dataqa and get X,Y,Z in minutes "

**Comment by dataqa** [comment]
I added some bullet points with the main selling points, I will probably refine these over time as I get more use cases. Thanks a lot!
