### ISSUE TITLE
The screenshots in the README don't help

### ISSUE THREAD

**Issue by talolard** [dataqa/dataqa#8]
The screenshots in the README don't look "nice" and don't help me understand what the tool does.

I'd consider replacing them with one video or animated gif that highlights the core differentiator of the tool, which is (rule based) search. 

Show me one quick video that makes me say wow instead of enumerating capabilities with screenshots

**Comment by dataqa** [comment]
Hi, thanks for the advice and totally agree they did not look great! I will create a video sometime in the future, but for now, I have replaced the images by gifs. Hopefully this makes it more lively.
